spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update   # options: validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 3001
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}


springdoc:
  api-docs:
    path: /users/v3/api-docs
  swagger-ui:
    path: /users/swagger-ui.html
  info:
    title: Users Service API
    version: 1.0
    description: Users microservice API


internal:
  service:
    token: ${INTERNAL_SERVICE_SECRET}

services:
  api:
    url: ${GATEWAY_API:http://localhost:8080}  # fallback for local dev if env var missing