spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # options: validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: users-service
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.wordium.users.dto.notification.NotificationEvent
        spring.json.trusted.packages: "*"        

server:
  port: 3001
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /users/v3/api-docs
  swagger-ui:
    path: /users/swagger-ui.html
  info:
    title: Users Service API
    version: 1.0
    description: Users microservice API

internal:
  service:
    token: ${INTERNAL_SERVICE_SECRET}

services:
  api:
    url: ${GATEWAY_API:http://localhost:8080} # fallback for local dev if env var missing

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
