server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # AUTH SERVICE
        - id: auth-service
          # uri: http://host.docker.internal:3000
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # AUTH SERVICE API-DOCS
        - id: auth-service-docs
          uri: http://${HOST}:3000
          predicates:
            - Path=/api/v1/auth/v3/api-docs/**
          filters:
            - StripPrefix=3


        # USERS SERVICE
        - id: users-service
          uri: http://${HOST}:3001
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        # USERS SERVICE API-DOCS
        - id: users-service-docs
          uri: http://${HOST}:3001
          predicates:
            - Path=/api/v1/users/v3/api-docs/**
          filters:
            - StripPrefix=3

        # WS-GATEWAY SERVICE
        
        - id: wsgateway-ws
          uri: ws://${HOST}:3002 
          # uri: lb://wsgateway
          predicates:
            - Path=/api/v1/wsgateway/ws/**
          filters:
            - StripPrefix=2
        - id: wsgateway-rest
          uri: http://${HOST}:3002
          # uri: lb://wsgateway
          predicates:
            - Path=/api/v1/wsgateway/**
          filters:
            - StripPrefix=2

        # TEST SERVICE
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/v1/test/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: users-service
        url: /api/v1/users/v3/api-docs
logging:
  level:
    reactor.netty.http.server: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.socket.server: DEBUG
