server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://host.docker.internal:3000  
          # uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: users-service
          uri: http://host.docker.internal:3001  
          # uri: lb://users-service
          predicates:
            - Path=/users-service/**
          filters:
            - StripPrefix=1

        - id: test-service
          uri: lb://test-service 
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
            # - JwtAuthFilter

eureka:
  client: 
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
