server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Enable Eureka-based dynamic routing
      # discovery:
      #   locator:
      #     enabled: true
          # lower-case-service-id: true  # optional: convert service IDs to lowercase
      routes:
        # Route for test1-service
        - id: auth
          uri: http://host.docker.internal:3000
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: test-service
          uri: lb://test-service 
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1

eureka:
  client: 
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
