server:
  port: 8080

spring:
  application:
    name: api-gateway
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: ${CLIENT_API}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service # http://${HOST}:3000
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # AUTH SERVICE API-DOCS
        - id: auth-service-docs
          uri: http://${HOST}:3000
          predicates:
            - Path=/api/v1/auth/v3/api-docs/**
          filters:
            - StripPrefix=3

        # USERS SERVICE
        - id: users-service
          uri: lb://users-service # http://${HOST}:3001
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        # USERS SERVICE API-DOCS
        - id: users-service-docs
          uri: http://${HOST}:3001
          predicates:
            - Path=/api/v1/users/v3/api-docs/**
          filters:
            - StripPrefix=3

        #  WS GATEWAY SERVICE HAVE TWO END POINT REST AND WS
        - id: wsgateway-rest
          uri: lb://wsgateway #http://${HOST}:3002
          predicates:
            - Path=/api/v1/wsgateway/**
          filters:
            - StripPrefix=2

        # wsgatway SERVICE API-DOCS
        - id: wsgateway-service-docs
          uri: lb://wsgateway
          predicates:
            - Path=/api/v1/wsgateway/v3/api-docs/**
          filters:
            - StripPrefix=3

        # POSTS SERVICE
        - id: posts-service
          uri: lb://posts-service #http://${HOST}:3003
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2

        # POSTS SERVICE
        - id: posts-service-docs
          uri: lb://posts-service
          predicates:
            - Path=/api/v1/posts/v3/api-docs/**
          filters:
            - StripPrefix=2

        # TEST SERVICE
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/v1/test/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: users-service
        url: /api/v1/users/v3/api-docs
      - name: wsgateway-service
        url: /api/v1/wsgateway/v3/api-docs
      - name: posts-service
        url: /api/v1/posts/v3/api-docs
logging:
  level:
    reactor.netty.http.server: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.web.reactive.socket.server: DEBUG
