
services:

  # servers
  eureka-server:
    build: ./backend/eurika-server/
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"

  
  api-gateway:
    build: ./backend/api-gatway/
    container_name: api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - "${API_GATWAY_PORT}:${API_GATWAY_PORT}"
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # cache
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    # volumes:
    #   - redis_data:/data
    restart: unless-stopped

  # message broaker 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # use local host for dev mode then move it to kafka service name 
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # databases
  auth_db:
    image: postgres:latest
    container_name: psql_auth_db
    env_file:
      - ./database/auth/.env  
    ports:
      - "${AUTH_DB_PORT}:${POSTGRES_PORT}"
      
  users_db:
    image: postgres:latest
    container_name: psql_users_db
    env_file:
      - ./database/users/.env  
    ports:
      - "${USERS_DB_PORT}:${POSTGRES_PORT}"
  notifications_db:
    image: postgres:latest
    container_name: psql_notifications_db
    env_file:
      - ./database/notifications/.env  
    ports:
      - "${NOTIFICATIONS_DB_PORT}:${POSTGRES_PORT}"

  # services 
  test-service:
    build: ./backend/test-service/
    container_name: test-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    depends_on:
      - eureka-server
  
  auth-service:
    build: ./backend/auth/
    container_name: auth-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=auth_db
    depends_on:
      - eureka-server
      - auth_db
    extra_hosts:
      - "host.docker.internal:host-gateway"


