
services:

  # servers
  eureka-server:
    build: ./backend/eurika-server/
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"

  
  api-gateway:
    build: ./backend/api-gatway/
    container_name: api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - "${API_GATWAY_PORT}:${API_GATWAY_PORT}"
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # cache
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  # message broaker 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1

      # Internal listener (for Docker containers)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"   # external port for host machine
      - "29092:29092" # optional: internal port for Docker network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # databases
  auth_db:
    image: postgres:latest
    container_name: psql_auth_db
    env_file:
      - ./database/auth/.env  
    ports:
      - "${AUTH_DB_PORT}:${POSTGRES_PORT}"
      
  users_db:
    image: postgres:latest
    container_name: psql_users_db
    env_file:
      - ./database/users/.env  
    ports:
      - "${USERS_DB_PORT}:${POSTGRES_PORT}"

  wsgateway_db:
    image: postgres:latest
    container_name: psql_wsgateway_db
    env_file:
      - ./database/wsgateway/.env  
    ports:
      - "${WSGATEWAY_DB_PORT}:${POSTGRES_PORT}"
  posts_db:
    image: postgres:latest
    container_name: psql_posts_db
    env_file:
      - ./database/posts/.env  
    ports:
      - "${POSTS_DB_PORT}:${POSTGRES_PORT}"
  # services 
  test-service:
    build: ./backend/test-service/
    container_name: test-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    depends_on:
      - eureka-server
  
  auth-service:
    build: ./backend/auth/
    container_name: auth-service
    env_file:
      - ./backend/auth/.env 
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=auth_db
    depends_on:
      - eureka-server
      - auth_db
      - api-gateway
    dns:
      - 8.8.8.8
      - 8.8.4.4

  wsgateway-service:
    build: ./backend/wsgateway/
    container_name: wsgateway-service
    env_file:
      - ./backend/wsgateway/.env 
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=wsgateway_db
    depends_on:
      - eureka-server
      - wsgateway_db
      - api-gateway
      - kafka
      - redis

  users-service:
    build: ./backend/users/
    container_name: users-service
    env_file:
      - ./backend/users/.env 
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=users_db
    depends_on:
      - eureka-server
      - api-gateway
      - kafka
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4


  posts-service:
    build: ./backend/posts/
    container_name: posts-service
    env_file:
      - ./backend/posts/.env 
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=posts_db
    depends_on:
      - eureka-server
      - api-gateway
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4


# frontend 
  frontend:
    build: ./frontend
    container_name: wordium-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    environment:
      - API_URL=http://api-gateway:8080 # Points to the Gateway

