
services:
  eureka-server:
    build: ./backend/eurika-server/
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    # networks:
    #   - backend
  
  # api-gateway:
  #   build: ./backend/api-gatway/
  #   container_name: api-gateway
  #   network_mode: "host"       # <-- host networking for direct access to localhost
  #   environment:
  #     - EUREKA_URL=http://localhost:${EUREKA_PORT}/eureka
  #   depends_on:
  #     - eureka-server

  # auth_db:
  #   image: postgres:latest
  #   container_name: psql_auth_db
  #   env_file:
  #     - ./database/auth/.env  
  #   ports:
  #     - "${AUTH_DB_PORT}:${POSTGRES_PORT}"
    # volumes:
    #   - auth_db_data:/var/lib/postgresql

# volumes:
  # users_db_data:
  # auth_db_data:

# networks:
#   backend:
#     driver: bridge
