
services:

  # servers
  eureka-server:
    build: ./backend/eurika-server/
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"

  
  api-gateway:
    build: ./backend/api-gatway/
    container_name: api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - "${API_GATWAY_PORT}:${API_GATWAY_PORT}"
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"



  # databases
  auth_db:
    image: postgres:latest
    container_name: psql_auth_db
    env_file:
      - ./database/auth/.env  
    ports:
      - "${AUTH_DB_PORT}:${POSTGRES_PORT}"
      
  users_db:
    image: postgres:latest
    container_name: psql_users_db
    env_file:
      - ./database/users/.env  
    ports:
      - "${USERS_DB_PORT}:${POSTGRES_PORT}"


  # services 
  test-service:
    build: ./backend/test-service/
    container_name: test-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    depends_on:
      - eureka-server
  
  auth-service:
    build: ./backend/auth/
    container_name: auth-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
      - POSTGRES_HOST=auth_db
    depends_on:
      - eureka-server
      - auth_db
    extra_hosts:
      - "host.docker.internal:host-gateway"


