
services:
  eureka-server:
    build: ./backend/eurika-server/
    container_name: eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
  
  api-gateway:
    build: ./backend/api-gatway/
    container_name: api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - "${API_GATWAY_PORT}:${API_GATWAY_PORT}"
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
  test-service:
    build: ./backend/test-service/
    container_name: test-service
    environment:
      - EUREKA_URL=http://eureka-server:${EUREKA_PORT}/eureka
    depends_on:
      - eureka-server
    # ports:
    #   - "${SERVICE_PORT}:${SERVICE_PORT}"


  auth_db:
    image: postgres:latest
    container_name: psql_auth_db
    env_file:
      - ./database/auth/.env  
    ports:
      - "${AUTH_DB_PORT}:${POSTGRES_PORT}"
    # volumes:
    #   - auth_db_data:/var/lib/postgresql

# volumes:
  # users_db_data:
  # auth_db_data:

# networks:
#   backend:
#     driver: bridge
