spring:
  application:
    name: notifications
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # options: validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

    consumer:
      group-id: notifications-service
      auto-offset-reset: earliest
      enable-auto-commit: true

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

server:
  port: 3002
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
    #   defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /notifications/v3/api-docs
  swagger-ui:
    path: /notifications/swagger-ui.html
  info:
    title: Notifications Service API
    version: 1.0
    description: Notifications microservice API
